pipeline {
    agent any
	
	environment {
        registry = "repository.k8sengineers.com/apexrepo/client"
        registryCredential = 'NexusRepoLogin'
    }
	
	stages {
	
	  stage(Build Image) {
	     steps {
		   dir(client/) {
		     script {
                dockerImage = docker.build registry + ":$BUILD_NUMBER"
             }
		   }
		 }
	  
	  }
	  
	  stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', registryCredential ) {
                dockerImage.push("$BUILD_NUMBER")
                dockerImage.push('latest')
              }
            }
          }
	   }
	}
}
